package org.cunoc.pdfpedia.domain.entity.monetary;

import static jakarta.persistence.GenerationType.IDENTITY;
import static lombok.AccessLevel.PRIVATE;

import java.math.BigDecimal;
import java.time.Instant;

import org.cunoc.pdfpedia.domain.entity.user.UserEntity;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.NonNull;
import lombok.RequiredArgsConstructor;

@Entity(name = "wallet")
@Table(name = "wallet", schema = "monetary_control")
@Data
@Builder(toBuilder = true)
@EqualsAndHashCode(of = "id")
@NoArgsConstructor
@RequiredArgsConstructor
@AllArgsConstructor(access = PRIVATE)
public class WalletEntity {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    private Long id;

    @NonNull
    @Column(nullable = false, precision = 10, scale = 2)
    private BigDecimal balance;

    @Column
    private boolean isDeleted;

    @OneToOne(mappedBy = "wallet", optional = false)
    private UserEntity user;

    @CreationTimestamp
    @Column
    private Instant createdAt;

    @UpdateTimestamp
    @Column
    private Instant updatedAt;
}

// CREATE TABLE monetary_control.wallets (
// id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
// user_id INT UNIQUE NOT NULL,
// balance DECIMAL(10,2) DEFAULT 0,
// is_deleted BOOLEAN DEFAULT false
// );