name: Deploy

on:
  workflow_run:
    workflows: Build
    branches:
      - main
      - dev
    types:
      - completed

jobs:
  deploy:
    name: Cloud Run Deploy
    runs-on: ubuntu-latest
    environment: "${{ github.ref_name == 'main' && 'prod' || 'dev' }}"
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      # BEGIN - Enviroment setup
      - name: Checkout code
        uses: actions/checkout@v4

      # END - Enviroment setup

      # BEGIN - GCP setup
      - name: Determine environment
        id: determine-env
        run: |
          # Determine environment based on branch
          if [ "${{ github.ref_name }}" == "main" ]; then
            echo "ENV=prod" >> $GITHUB_ENV
          else
            echo "ENV=dev" >> $GITHUB_ENV
          fi

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_DEPLOY_SA }}

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # END - GCP setup

      # BEGIN - Deploy
      - name: Deploy to Cloud Run
        uses: "google-github-actions/deploy-cloudrun@v2"
        with:
          image: "${{ secrets.GCP_LOCATION }}/pdfpedia-${{ env.ENV  }}:latest"
          region: ${{ secrets.GCP_REGION }}
          env-vars: |-
            DB_USER=${{ secrets.DB_USER }}
            DB_PASS=${{ secrets.DB_PASS }}
            DB_HOST=${{ secrets.DB_HOST }}
            DB_DATABASE=${{ secrets.DB_DATABASE }}

            EMAIL_ADDRESS=${{ secrets.EMAIL_ADDRESS }}
            EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}

            STORAGE_CLOUD_NAME=${{ secrets.STORAGE_CLOUD_NAME }}
            STORAGE_API_KEY=${{ secrets.STORAGE_API_KEY }}
            STORAGE_API_SECRET=${{ secrets.STORAGE_API_SECRET }}

      # END - Deploy
