name: Test

on:
  push:
    branches:
      - main
      - dev

  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    name: Spring Boot Test
    runs-on: ubuntu-latest
    environment: "${{ github.ref_name == 'main' && 'prod' || 'dev' }}"
    env: ${{ secrets }}
    steps:
      # BEGIN - Enviroment setup
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4

      # END - Enviroment setup

      # BEGIN - Gradle test tasks
      - name: Test with gradle
        run: ./gradlew clean test

      - name: Test coverage with jacoco
        run: ./gradlew jacocoTestReport jacocoTestCoverageVerification

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ${{ github.workspace }}/build/reports/jacoco/test/jacoco.xml
          overwrite: true
          retention-days: 7

      # END - Gradle test tasks
